### ISSUE TITLE
Incorrect Gradle version shown in Build Scan 'Performance Settings and Suggestions'

### ISSUE THREAD

**Issue by gazbert** [gradle/gradle-build-scan-quickstart#2]
Not sure if this is right place to raise issues for the Build scan plugin? I couldn't find the plugin repo listed on https://github.com/gradle.

When viewing a Build scan, the Summary correctly shows Gradle 4.0, but the Performance -> Settings and Suggestions shows:

`Build was run with the latest Gradle version (3.5.1)`

I've recently updated to Gradle wrapper 4.0 from 3.5.1 and am using Build scan plugin 1.8.

```
gazbert@pegasus:~/IdeaProjects/bxbot$ ./gradlew -v

------------------------------------------------------------
Gradle 4.0
------------------------------------------------------------

Build time:   2017-06-14 15:11:08 UTC
Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Linux 3.16.0-4-amd64 amd64

gazbert@pegasus:~/IdeaProjects/bxbot$ 

```

The build is here:
https://gradle.com/s/2o7si77rurvdw

It is reproducible. Happy to help if I can.

**Comment by facewindu** [comment]
Hi,

Thanks for reporting.
I'm currently providing a fix for this.

PS:  next time, https://discuss.gradle.org/c/help-discuss/cloud-services would be a better place to report bugs or suggestions.

**Comment by gazbert** [comment]
No problem - will use the forum in future. Cheers!
