### ISSUE TITLE
Publishing build scan failed due to network error 'java.net.SocketException: Unexpected end of file from server'

### ISSUE THREAD

**Issue by floroz** [gradle/gradle-build-scan-quickstart#33]
I am following the instruction to create a Build Scan using the starter project.

After cloning the repository, and running `./gradlew build --scan` I continue getting the same error

```sh
BUILD SUCCESSFUL in 616ms
4 actionable tasks: 4 up-to-date

Publishing a build scan to scans.gradle.com requires accepting the Gradle Terms of Service defined at https://gradle.com/terms-of-service. Do you accept these terms? [yes, no] yes

Gradle Terms of Service accepted.

Publishing build scan...
Publishing build scan failed due to network error 'java.net.SocketException: Unexpected end of file from server' (2 retries remaining)...
Publishing build scan failed due to network error 'java.net.SocketException: Unexpected end of file from server' (1 retry remaining)...

A network error occurred.

If you require assistance with this problem, please report it via https://gradle.com/help/plugin and include the following information via copy/paste.

----------
Gradle version: 7.5.1
Plugin version: 3.11.4
Request URL: https://status.gradle.com
Request ID: 0e3d00fe-9421-4f38-bea9-8c5ac72a6720
Exception: java.net.SocketException: Unexpected end of file from server
----------
```
MacOS: 12.4 

Java version installed:

<img width="380" alt="Screenshot 2022-11-10 at 15 31 17" src="https://user-images.githubusercontent.com/45793869/201118493-d1e45b9f-672a-4c37-b09d-253382cea0f5.png">

**Comment by guylabs** [comment]
Hi @floroz 

There was an upgrade of scans.gradle.com and you may just hit that time slot. Can you try again please?

Thanks!

**Comment by floroz** [comment]
> Hi @floroz
> 
> There was an upgrade of scans.gradle.com and you may just hit that time slot. Can you try again please?
> 
> Thanks!

Thanks! I confirm it's now working :)
