### ISSUE TITLE
Build scan cannot be created because the build scan plugin was not applied

### ISSUE THREAD

**Issue by rocketraman** [gradle/gradle-build-scan-quickstart#6]
```
$ git clone git@github.com:gradle/gradle-build-scan-quickstart.git gradle-build-scan-quickstart
$ cd gradle-build-scan-quickstart/
$ ./gradlew --version

------------------------------------------------------------
Gradle 4.9
------------------------------------------------------------

Build time:   2018-07-16 08:14:03 UTC
Revision:     efcf8c1cf533b03c70f394f270f46a174c738efc

Kotlin DSL:   0.18.4
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_171 (Oracle Corporation 25.171-b11)
OS:           Linux 4.17.12-100.fc27.x86_64 amd64

$ ./gradlew build --scan
Build scan cannot be created because the build scan plugin was not applied.                                                                                                                                                        
For more information on how to apply the build scan plugin, please visit https://gradle.com/scans/help/gradle-cli.                                                                                                                 

BUILD SUCCESSFUL in 3s
4 actionable tasks: 4 executed
```

**Comment by breskeby** [comment]
Hello Raman,
thanks for your report.  Unfortunately following exactly your steps does not reproduce your problem for me. The expected behaviour here would be for the plugin to ask you to agree the license agreement on the console. But it seems this step didn't happen at all. Can you check if manually applying the plugin works for you by adding 
```
plugins {
  id 'com.gradle.build-scan' version '1.15.2'
}

buildScan {
    termsOfServiceUrl = 'https://gradle.com/terms-of-service'
    termsOfServiceAgree = 'yes'
}
``` 

another thing to try is to run your build again with the debug flag ( `-d`) and provide me the output (warning: the -d flag generates a lot of of output)?

**Comment by rocketraman** [comment]
Something definitely seems odd in my environment. Adding the plugin explicitly does not fix the problem. Here is the output:

```
* What went wrong:
A problem occurred evaluating root project 'gradle-build-scan-quickstart'.
> Could not set unknown property 'termsOfServiceUrl' for object of type com.gradle.scan.plugin.BuildScanExtension.
```

It appears to be trying to use an older 1.0 version of the plugin. Here is the output from `-d`:

[build.log](https://github.com/gradle/gradle-build-scan-quickstart/files/2299596/build.log)

**Comment by rocketraman** [comment]
I deleted everything inside `.gradle` and that seems to have fixed the problem. I probably should have kept a copy of it for analysis, but unfortunately I did not.

**Comment by deanhiller** [comment]
Man, I just hit this in 4.10.3 and turned out, I had an old build scan plugin installed (1.0) and upgrading to the above snippet fixed me but before that, there was no good output on the version mismatch so it was a PITA to figure out at first as I didn't know the plugin was already installed.
